const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

test("streaming AI panel exposes synced text areas and usable actions", () => {
  const html = fs.readFileSync(path.join(__dirname, "../src/streaming-ai/index.html"), "utf8");
  const script = fs.readFileSync(path.join(__dirname, "../src/streaming-ai/streaming-ai.js"), "utf8");

  assert.equal(html.includes('id="raw-text"'), true);
  assert.equal(html.includes('id="ai-text"'), true);
  assert.equal(html.includes('id="status-meta"'), true);
  assert.equal(html.includes('id="copy-raw-button"'), true);
  assert.equal(html.includes('id="copy-ai-button"'), true);
  assert.equal(html.includes('id="clear-button"'), true);
  assert.equal(html.includes('id="apply-refined-raw-button"'), true);
  assert.equal(html.includes('id="apply-ai-button"'), true);
  assert.equal(html.includes('id="streaming-scenario-select"'), true);
  assert.equal(html.includes('value="official_notice"'), true);
  assert.equal(html.includes('value="official_resolution"'), true);
  assert.equal(html.includes('value="business_plan"'), true);
  assert.equal(html.includes('value="student_leave_note"'), true);
  assert.equal(html.includes("党政机关公文"), true);
  assert.equal(html.includes("公司/白领常用"), true);
  assert.equal(html.includes("学生/校园常用"), true);
  assert.equal(html.includes("AI 修正原文"), true);
  assert.equal(html.includes("refined_raw_text"), true);
  assert.equal(html.includes("can_apply_refined_raw"), true);
  assert.equal(html.includes("rewrite_scenario_label"), true);
  assert.equal(html.includes("subscribeStreamingAiPanelState(render)"), true);
  assert.equal(html.includes("getStreamingAiPanelState()"), true);
  assert.equal(html.includes("copyStreamingAiRaw()"), true);
  assert.equal(html.includes("copyStreamingAiSummary()"), true);
  assert.equal(html.includes("applyStreamingAiRefinedRaw()"), true);
  assert.equal(html.includes("applyStreamingAiSummary()"), true);
  assert.equal(html.includes("setStreamingAiScenario"), true);
  assert.equal(html.includes("clearStreamingAiPanel()"), true);
  assert.equal(script.includes("applyRefinedRawButton"), true);
  assert.equal(script.includes("applyAiButton"), true);
  assert.equal(script.includes("scenarioSelect"), true);
  assert.equal(script.includes("refined_raw_text"), true);
  assert.equal(script.includes("can_apply_refined_raw"), true);
  assert.equal(script.includes("rewrite_scenario_label"), true);
  assert.equal(script.includes("subscribeStreamingAiPanelState(render)"), true);
  assert.equal(script.includes("getStreamingAiPanelState()"), true);
  assert.equal(script.includes("copyStreamingAiRaw()"), true);
  assert.equal(script.includes("copyStreamingAiSummary()"), true);
  assert.equal(script.includes("applyStreamingAiRefinedRaw()"), true);
  assert.equal(script.includes("applyStreamingAiSummary()"), true);
  assert.equal(script.includes("setStreamingAiScenario"), true);
  assert.equal(script.includes("clearStreamingAiPanel()"), true);
});
